version: "3.7"

services:
  kalturavods_api:
    container_name: kalturavods_api
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 app:APP
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kalturavods.rule=Host(`api.kalturavods.jorgenson.dev`)"
      - "traefik.http.routers.kalturavods.tls=true"
      - "traefik.http.routers.kalturavods.tls.certresolver=letsencrypt"
      - "traefik.http.routers.kalturavods.entrypoints=https"
      - "traefik.docker.network=web"
    depends_on:
      - kalturavods_db
    ports:
      - 8000:5000
    environment:
      - POSTGRES_PASSWORD=kalturavods
    env_file:
      - docker/api.env
      - docker/db.env
    networks:
      - kalturavods_internal
      - web
  kalturavods_db:
    image: postgres:12-alpine
    container_name: kalturavods_db
    environment:
      - POSTGRES_PASSWORD=kalturavods
    env_file:
      - docker/db.env
    labels:
      - "traefik.enable=false"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    networks:
      - kalturavods_internal


networks:
  kalturavods_internal:
  web:
    external:
      name: web
