name: Kalturavods API unittests.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build with docker-compose and run unit tests.
        run: |
          docker network create web
          docker-compose up -d --build
#          docker-compose exec -T kalturavods_api flask db upgrade
#          docker-compose exec -T kalturavods_api python -m unittest

  tag-image:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - name: Tag image
        run: |
          echo -n ${{ secrets.DOCKER_HUB_PASS }} | docker login -u nymann --password-stdin
          docker build -t kalturavods/api:production -f docker/Dockerfile .
          docker push kalturavods/api:production